name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  app:
    name: App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version: lts/*
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run type-check

  studio:
    name: Studio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version: lts/*
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec tsc --noEmit
