/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Topic = {
  _id: string
  _type: 'topic'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  icon?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  planTier?: 'starter' | 'growth' | 'enterprise'
  priceMonthly?: number
  channels?: Array<string>
  seatLimit?: number
  features?: Array<string>
  icon?: string
}

export type InternalCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'internalCategory'
}

export type Policy = {
  _id: string
  _type: 'policy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  summary?: string
  content?: BlockContent
  internalCategory?: InternalCategoryReference
  importance?: 'standard' | 'critical'
  status?: 'draft' | 'published' | 'archived'
  owner?: string
  lastReviewedAt?: string
  reviewByDate?: string
}

export type InternalCategory = {
  _id: string
  _type: 'internalCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type TopicReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'topic'
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: BlockContent
  audience?: Array<string>
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  topics?: Array<
    {
      _key: string
    } & TopicReference
  >
  status?: 'draft' | 'published' | 'archived'
}

export type HelpArticle = {
  _id: string
  _type: 'helpArticle'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  summary?: string
  content?: BlockContent
  audience?: Array<string>
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  topics?: Array<
    {
      _key: string
    } & TopicReference
  >
  status?: 'draft' | 'published' | 'archived'
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | BlockContent
  | Topic
  | Slug
  | Product
  | InternalCategoryReference
  | Policy
  | InternalCategory
  | ProductReference
  | TopicReference
  | Faq
  | HelpArticle
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../app/sanity/queries.ts
// Variable: articlesQuery
// Query: *[    _type == "helpArticle" && status == "published" && defined(slug.current)    && ($product == null || $product in products[]->slug.current)    && ($topic == null || $topic in topics[]->slug.current)  ] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    "products": products[]->{ _id, title, "slug": slug.current },    "topics": topics[]->{ _id, title, "slug": slug.current },  }
export type ArticlesQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  summary: string | null
  products: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
  topics: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
}>

// Source: ../app/sanity/queries.ts
// Variable: articleQuery
// Query: *[_type == "helpArticle" && slug.current == $slug] [0] {    _id,    title,    "slug": slug.current,    summary,    content,    "products": products[]->{ _id, title, "slug": slug.current },    "topics": topics[]->{ _id, title, "slug": slug.current },  }
export type ArticleQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  summary: string | null
  content: BlockContent | null
  products: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
  topics: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
} | null

// Source: ../app/sanity/queries.ts
// Variable: articleSlugsQuery
// Query: *[_type == "helpArticle" && defined(slug.current)]  {"slug": slug.current}
export type ArticleSlugsQueryResult = Array<{
  slug: string | null
}>

// Source: ../app/sanity/queries.ts
// Variable: productsQuery
// Query: *[_type == "product"] | order(title asc) { _id, title, "slug": slug.current }
export type ProductsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
}>

// Source: ../app/sanity/queries.ts
// Variable: topicsQuery
// Query: *[_type == "topic"] | order(title asc) { _id, title, "slug": slug.current }
export type TopicsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[\n    _type == "helpArticle" && status == "published" && defined(slug.current)\n    && ($product == null || $product in products[]->slug.current)\n    && ($topic == null || $topic in topics[]->slug.current)\n  ] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    "products": products[]->{ _id, title, "slug": slug.current },\n    "topics": topics[]->{ _id, title, "slug": slug.current },\n  }\n': ArticlesQueryResult
    '\n  *[_type == "helpArticle" && slug.current == $slug] [0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    content,\n    "products": products[]->{ _id, title, "slug": slug.current },\n    "topics": topics[]->{ _id, title, "slug": slug.current },\n  }\n': ArticleQueryResult
    '\n  *[_type == "helpArticle" && defined(slug.current)]\n  {"slug": slug.current}\n': ArticleSlugsQueryResult
    '\n  *[_type == "product"] | order(title asc) { _id, title, "slug": slug.current }\n': ProductsQueryResult
    '\n  *[_type == "topic"] | order(title asc) { _id, title, "slug": slug.current }\n': TopicsQueryResult
  }
}
