/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SyncState = {
  _type: 'syncState'
  status?: 'never' | 'pending' | 'synced' | 'failed'
  lastSyncedAt?: string
  error?: string
}

export type VariantOverride = {
  _type: 'variantOverride'
  audienceTag?: string
  banner?: Banner
  faceout?: Faceout
  editorialTiles?: Array<
    {
      _key: string
    } & EditorialTile
  >
}

export type FacetConfig = {
  _type: 'facetConfig'
  facetHandle?: string
  labelOverride?: string
}

export type ProductBadgeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productBadge'
}

export type BadgeAssignment = {
  _type: 'badgeAssignment'
  product?: Product
  badge?: ProductBadgeReference
  customLabel?: string
  startDate?: string
  endDate?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type EditorialTile = {
  _type: 'editorialTile'
  position?: number
  headline?: string
  body?: BlockContent
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  ctaLabel?: string
  ctaHref?: string
  theme?: 'yellow' | 'orange' | 'blue' | 'black' | 'gray'
}

export type Faceout = {
  _type: 'faceout'
  product?: Product
  variantGid?: string
  editorialHeadline?: string
  imageOverride?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Banner = {
  _type: 'banner'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  headline?: string
  subhead?: string
  ctaLabel?: string
  ctaHref?: string
  theme?: 'yellow' | 'orange' | 'blue' | 'black' | 'gray'
}

export type Product = {
  _type: 'product'
  productGid?: string
  productTitle?: string
  productImageUrl?: string
}

export type ProductBadge = {
  _id: string
  _type: 'productBadge'
  _createdAt: string
  _updatedAt: string
  _rev: string
  label?: string
  slug?: Slug
  color?: 'sale' | 'new' | 'final-sale' | 'best-seller' | 'neutral'
  icon?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type CollectionEnrichment = {
  _id: string
  _type: 'collectionEnrichment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  handle?: Slug
  collectionType?: 'shopify-native' | 'sanity-custom'
  title?: string
  banner?: Banner
  faceout?: Faceout
  productList?: Array<
    {
      _key: string
    } & Product
  >
  pinnedRecs?: Array<
    {
      _key: string
    } & Product
  >
  editorialTiles?: Array<
    {
      _key: string
    } & EditorialTile
  >
  badges?: Array<
    {
      _key: string
    } & BadgeAssignment
  >
  facetConfig?: Array<
    {
      _key: string
    } & FacetConfig
  >
  variantOverrides?: Array<
    {
      _key: string
    } & VariantOverride
  >
  syncStatus?: SyncState
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | BlockContent
  | SyncState
  | VariantOverride
  | FacetConfig
  | ProductBadgeReference
  | BadgeAssignment
  | SanityImageAssetReference
  | EditorialTile
  | Faceout
  | Banner
  | Product
  | ProductBadge
  | Slug
  | CollectionEnrichment
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../frontend/sanity/queries.ts
// Variable: collectionEnrichmentQuery
// Query: *[_type == "collectionEnrichment" && handle.current == $handle][0]{    "handle": handle.current,    collectionType,    title,    banner {"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},    faceout {  "productGid": product.productGid,  variantGid,  editorialHeadline,  "imageUrlOverride": imageOverride.asset->url},    editorialTiles[] {position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},    badges[]{      "productGid": product.productGid,      "badge": badge->{"slug": slug.current, label, color, icon},      customLabel,      startDate,      endDate    },    facetConfig[]{facetHandle, labelOverride},    productList[]{"productGid": productGid},    variantOverrides[]{      audienceTag,      banner {"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},      faceout {  "productGid": product.productGid,  variantGid,  editorialHeadline,  "imageUrlOverride": imageOverride.asset->url},      editorialTiles[] {position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme}    },    "syncStatus": syncStatus.status  }
export type CollectionEnrichmentQueryResult = {
  handle: string | null
  collectionType: 'sanity-custom' | 'shopify-native' | null
  title: string | null
  banner: {
    imageUrl: string | null
    headline: string | null
    subhead: string | null
    ctaLabel: string | null
    ctaHref: string | null
    theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
  } | null
  faceout: {
    productGid: string | null
    variantGid: string | null
    editorialHeadline: string | null
    imageUrlOverride: string | null
  } | null
  editorialTiles: Array<{
    position: number | null
    imageUrl: string | null
    headline: string | null
    body: BlockContent | null
    ctaLabel: string | null
    ctaHref: string | null
    theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
  }> | null
  badges: Array<{
    productGid: string | null
    badge: {
      slug: string | null
      label: string | null
      color: 'best-seller' | 'final-sale' | 'neutral' | 'new' | 'sale' | null
      icon: string | null
    } | null
    customLabel: string | null
    startDate: string | null
    endDate: string | null
  }> | null
  facetConfig: Array<{
    facetHandle: string | null
    labelOverride: string | null
  }> | null
  productList: Array<{
    productGid: string | null
  }> | null
  variantOverrides: Array<{
    audienceTag: string | null
    banner: {
      imageUrl: string | null
      headline: string | null
      subhead: string | null
      ctaLabel: string | null
      ctaHref: string | null
      theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
    } | null
    faceout: {
      productGid: string | null
      variantGid: string | null
      editorialHeadline: string | null
      imageUrlOverride: string | null
    } | null
    editorialTiles: Array<{
      position: number | null
      imageUrl: string | null
      headline: string | null
      body: BlockContent | null
      ctaLabel: string | null
      ctaHref: string | null
      theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
    }> | null
  }> | null
  syncStatus: 'failed' | 'never' | 'pending' | 'synced' | null
} | null

// Source: ../frontend/sanity/queries.ts
// Variable: allCollectionsQuery
// Query: *[_type == "collectionEnrichment" && defined(handle.current)] | order(handle.current asc){    "handle": handle.current,    "title": coalesce(title, handle.current),    collectionType,    "bannerImageUrl": banner.image.asset->url,    "theme": coalesce(banner.theme, "yellow")  }
export type AllCollectionsQueryResult = Array<{
  handle: string | null
  title: string | null
  collectionType: 'sanity-custom' | 'shopify-native' | null
  bannerImageUrl: string | null
  theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow'
}>

// Source: ../frontend/sanity/queries.ts
// Variable: collectionHandlesQuery
// Query: *[_type == "collectionEnrichment" && defined(handle.current)]{"handle": handle.current}
export type CollectionHandlesQueryResult = Array<{
  handle: string | null
}>

// Source: ../functions/badge-resync/index.ts
// Variable: AFFECTED_QUERY
// Query: *[_type == "collectionEnrichment" && $badgeId in badges[].badge._ref]{    "handle": handle.current,    collectionType,    title,    banner{"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},    faceout{      "productGid": product.productGid,      variantGid,      editorialHeadline,      "imageUrlOverride": imageOverride.asset->url    },    editorialTiles[]{position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},    badges[]{      "productGid": product.productGid,      "badge": badge->{"slug": slug.current, label, color, icon},      customLabel, startDate, endDate    },    facetConfig[]{facetHandle, labelOverride},    productList[]{"productGid": productGid}  }
export type AFFECTED_QUERY_RESULT = Array<{
  handle: string | null
  collectionType: 'sanity-custom' | 'shopify-native' | null
  title: string | null
  banner: {
    imageUrl: string | null
    headline: string | null
    subhead: string | null
    ctaLabel: string | null
    ctaHref: string | null
    theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
  } | null
  faceout: {
    productGid: string | null
    variantGid: string | null
    editorialHeadline: string | null
    imageUrlOverride: string | null
  } | null
  editorialTiles: Array<{
    position: number | null
    imageUrl: string | null
    headline: string | null
    body: BlockContent | null
    ctaLabel: string | null
    ctaHref: string | null
    theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
  }> | null
  badges: Array<{
    productGid: string | null
    badge: {
      slug: string | null
      label: string | null
      color: 'best-seller' | 'final-sale' | 'neutral' | 'new' | 'sale' | null
      icon: string | null
    } | null
    customLabel: string | null
    startDate: string | null
    endDate: string | null
  }> | null
  facetConfig: Array<{
    facetHandle: string | null
    labelOverride: string | null
  }> | null
  productList: Array<{
    productGid: string | null
  }> | null
}>

// Source: ../functions/collection-sync/index.ts
// Variable: ENRICHMENT_QUERY
// Query: *[_id == $id][0]{  "handle": handle.current,  collectionType,  title,  banner{"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},  faceout{    "productGid": product.productGid,    variantGid,    editorialHeadline,    "imageUrlOverride": imageOverride.asset->url  },  editorialTiles[]{position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},  badges[]{    "productGid": product.productGid,    "badge": badge->{"slug": slug.current, label, color, icon},    customLabel, startDate, endDate  },  facetConfig[]{facetHandle, labelOverride},  productList[]{"productGid": productGid}}
export type ENRICHMENT_QUERY_RESULT =
  | {
      handle: null
      collectionType: null
      title: null
      banner: null
      faceout: null
      editorialTiles: null
      badges: null
      facetConfig: null
      productList: null
    }
  | {
      handle: null
      collectionType: null
      title: string | null
      banner: null
      faceout: null
      editorialTiles: null
      badges: null
      facetConfig: null
      productList: null
    }
  | {
      handle: string | null
      collectionType: 'sanity-custom' | 'shopify-native' | null
      title: string | null
      banner: {
        imageUrl: string | null
        headline: string | null
        subhead: string | null
        ctaLabel: string | null
        ctaHref: string | null
        theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
      } | null
      faceout: {
        productGid: string | null
        variantGid: string | null
        editorialHeadline: string | null
        imageUrlOverride: string | null
      } | null
      editorialTiles: Array<{
        position: number | null
        imageUrl: string | null
        headline: string | null
        body: BlockContent | null
        ctaLabel: string | null
        ctaHref: string | null
        theme: 'black' | 'blue' | 'gray' | 'orange' | 'yellow' | null
      }> | null
      badges: Array<{
        productGid: string | null
        badge: {
          slug: string | null
          label: string | null
          color: 'best-seller' | 'final-sale' | 'neutral' | 'new' | 'sale' | null
          icon: string | null
        } | null
        customLabel: string | null
        startDate: string | null
        endDate: string | null
      }> | null
      facetConfig: Array<{
        facetHandle: string | null
        labelOverride: string | null
      }> | null
      productList: Array<{
        productGid: string | null
      }> | null
    }
  | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "collectionEnrichment" && handle.current == $handle][0]{\n    "handle": handle.current,\n    collectionType,\n    title,\n    banner {"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},\n    faceout {\n  "productGid": product.productGid,\n  variantGid,\n  editorialHeadline,\n  "imageUrlOverride": imageOverride.asset->url\n},\n    editorialTiles[] {position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},\n    badges[]{\n      "productGid": product.productGid,\n      "badge": badge->{"slug": slug.current, label, color, icon},\n      customLabel,\n      startDate,\n      endDate\n    },\n    facetConfig[]{facetHandle, labelOverride},\n    productList[]{"productGid": productGid},\n    variantOverrides[]{\n      audienceTag,\n      banner {"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},\n      faceout {\n  "productGid": product.productGid,\n  variantGid,\n  editorialHeadline,\n  "imageUrlOverride": imageOverride.asset->url\n},\n      editorialTiles[] {position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme}\n    },\n    "syncStatus": syncStatus.status\n  }\n': CollectionEnrichmentQueryResult
    '\n  *[_type == "collectionEnrichment" && defined(handle.current)] | order(handle.current asc){\n    "handle": handle.current,\n    "title": coalesce(title, handle.current),\n    collectionType,\n    "bannerImageUrl": banner.image.asset->url,\n    "theme": coalesce(banner.theme, "yellow")\n  }\n': AllCollectionsQueryResult
    '\n  *[_type == "collectionEnrichment" && defined(handle.current)]{"handle": handle.current}\n': CollectionHandlesQueryResult
    '\n  *[_type == "collectionEnrichment" && $badgeId in badges[].badge._ref]{\n    "handle": handle.current,\n    collectionType,\n    title,\n    banner{"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},\n    faceout{\n      "productGid": product.productGid,\n      variantGid,\n      editorialHeadline,\n      "imageUrlOverride": imageOverride.asset->url\n    },\n    editorialTiles[]{position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},\n    badges[]{\n      "productGid": product.productGid,\n      "badge": badge->{"slug": slug.current, label, color, icon},\n      customLabel, startDate, endDate\n    },\n    facetConfig[]{facetHandle, labelOverride},\n    productList[]{"productGid": productGid}\n  }\n': AFFECTED_QUERY_RESULT
    '*[_id == $id][0]{\n  "handle": handle.current,\n  collectionType,\n  title,\n  banner{"imageUrl": image.asset->url, headline, subhead, ctaLabel, ctaHref, theme},\n  faceout{\n    "productGid": product.productGid,\n    variantGid,\n    editorialHeadline,\n    "imageUrlOverride": imageOverride.asset->url\n  },\n  editorialTiles[]{position, "imageUrl": image.asset->url, headline, body, ctaLabel, ctaHref, theme},\n  badges[]{\n    "productGid": product.productGid,\n    "badge": badge->{"slug": slug.current, label, color, icon},\n    customLabel, startDate, endDate\n  },\n  facetConfig[]{facetHandle, labelOverride},\n  productList[]{"productGid": productGid}\n}': ENRICHMENT_QUERY_RESULT
  }
}
