packages:
  - studio
  - frontend
  - functions
  - e2e
  - apps/*
  - packages/*

catalog:
  sanity: '^5.21.0'
  '@sanity/client': '^7.21.0'
  '@sanity/icons': '^3.7.4'
  '@sanity/vision': '^5.21.0'
  groq: '^5.21.0'
  react: '^19.2.5'
  react-dom: '^19.2.5'
  '@types/react': '^19.2'
  '@types/react-dom': '^19.2.3'
  styled-components: '^6.4.0'
  typescript: '^5'
  mjml: '^5.0.1'
