packages:
  - studio
  - frontend
  - functions
  - e2e
  - apps/*
  - packages/*

catalog:
  '@sanity/client': '^7.22.0'
  '@sanity/icons': '^3.7.4'
  '@sanity/vision': '^5.22.0'
  '@types/react': '^19.2.14'
  '@types/react-dom': '^19.2.3'
  groq: '^5.22.0'
  mjml: '^5.0.1'
  react: '^19.2.5'
  react-dom: '^19.2.5'
  sanity: '^5.22.0'
  styled-components: '^6.4.1'
  typescript: '^5.9.3'
