packages:
  - studio
  - frontend
  - functions
  - packages/@starter/*

catalog:
  sanity: '^5.18.0'
  '@sanity/client': '^7.20.0'
  '@sanity/icons': '^3.7.4'
  '@sanity/vision': '^5.18.0'
  groq: '^5.18.0'
  react: '^19.2.4'
  react-dom: '^19.2.4'
  '@types/react': '^19.2'
  '@types/react-dom': '^19.2.3'
  styled-components: '^6.3.12'
  typescript: '^5.9.3'
  mjml: '^5.0.0-alpha.5'
  '@types/mjml': '^4.7.4'
