/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type AttributeRuleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'attributeRule'
}

export type ProductTypeScope = {
  _type: 'productTypeScope'
  productType?: string
  priorityList?: Array<
    {
      _key: string
    } & AttributeRuleReference
  >
}

export type ExamplePhrase = {
  _type: 'examplePhrase'
  do?: string
  dont?: string
}

export type BrandVoiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brandVoice'
}

export type AiEnrichment = {
  _type: 'aiEnrichment'
  generatedAt?: string
  generationContext?: BrandVoiceReference
  reviewNotes?: BlockContent
  reviewedBy?: string
  reviewedAt?: string
}

export type Product = {
  _type: 'product'
  productGid?: string
  productTitle?: string
  productImageUrl?: string
}

export type BrandVoice = {
  _id: string
  _type: 'brandVoice'
  _createdAt: string
  _updatedAt: string
  _rev: string
  persona?: BlockContent
  toneGuidance?: BlockContent
  contextPrompt?: string
  examplePhrases?: Array<
    {
      _key: string
    } & ExamplePhrase
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SkuEnrichment = {
  _id: string
  _type: 'skuEnrichment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  product?: Product
  headline?: string
  editorialCopy?: BlockContent
  lifestyleImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  launchBadge?: string
  status?: 'draft' | 'approved'
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type ControlPlane = {
  _id: string
  _type: 'controlPlane'
  _createdAt: string
  _updatedAt: string
  _rev: string
  priorityList?: Array<
    {
      _key: string
    } & AttributeRuleReference
  >
  productTypeScopes?: Array<
    {
      _key: string
    } & ProductTypeScope
  >
}

export type AttributeRule = {
  _id: string
  _type: 'attributeRule'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  category?: 'care' | 'fit' | 'lifestyle' | 'spec' | 'launch'
  description?: BlockContent
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tags?: Array<string>
  excludedTags?: Array<string>
  language?: string
  order?: number
  status?: 'draft' | 'in-review' | 'approved'
  aiGenerated?: boolean
  aiEnrichment?: AiEnrichment
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | BlockContent
  | AttributeRuleReference
  | ProductTypeScope
  | ExamplePhrase
  | BrandVoiceReference
  | AiEnrichment
  | Product
  | BrandVoice
  | SanityImageAssetReference
  | SkuEnrichment
  | SanityImageCrop
  | SanityImageHotspot
  | ControlPlane
  | AttributeRule
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: ../frontend/sanity/queries.ts
// Variable: controlPlaneQuery
// Query: *[_type == "controlPlane" && _id == "controlPlane"][0]{    "priorityList": priorityList[]->{  _id,  name,  category,  description,  "iconUrl": icon.asset->url,  "tags": coalesce(tags, []),  "excludedTags": coalesce(excludedTags, []),  language,  "order": coalesce(order, 0),  status},    "productTypeScopes": productTypeScopes[]{      productType,      "ruleIds": priorityList[]._ref    }  }
export type ControlPlaneQueryResult = {
  priorityList: Array<{
    _id: string
    name: string | null
    category: 'care' | 'fit' | 'launch' | 'lifestyle' | 'spec' | null
    description: BlockContent | null
    iconUrl: string | null
    tags: Array<string> | Array<never>
    excludedTags: Array<string> | Array<never>
    language: string | null
    order: number | 0
    status: 'approved' | 'draft' | 'in-review' | null
  }> | null
  productTypeScopes: Array<{
    productType: string | null
    ruleIds: Array<string> | null
  }> | null
} | null

// Source: ../frontend/sanity/queries.ts
// Variable: skuEnrichmentByGidQuery
// Query: *[_type == "skuEnrichment" && status == "approved" && product.productGid == $gid][0]{    "productGid": product.productGid,    headline,    editorialCopy,    "lifestyleImages": lifestyleImages[]{      "url": asset->url,      "altText": asset->altText    },    launchBadge,    status  }
export type SkuEnrichmentByGidQueryResult = {
  productGid: string | null
  headline: string | null
  editorialCopy: BlockContent | null
  lifestyleImages: Array<{
    url: string | null
    altText: string | null
  }> | null
  launchBadge: string | null
  status: 'approved' | 'draft' | null
} | null

// Source: ../functions/review-stamp/index.ts
// Variable: RULE_QUERY
// Query: *[_id == $id][0]{status, "reviewedAt": aiEnrichment.reviewedAt}
export type RULE_QUERY_RESULT =
  | {
      status: null
      reviewedAt: null
    }
  | {
      status: 'approved' | 'draft' | null
      reviewedAt: null
    }
  | {
      status: 'approved' | 'draft' | 'in-review' | null
      reviewedAt: string | null
    }
  | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "controlPlane" && _id == "controlPlane"][0]{\n    "priorityList": priorityList[]->{\n  _id,\n  name,\n  category,\n  description,\n  "iconUrl": icon.asset->url,\n  "tags": coalesce(tags, []),\n  "excludedTags": coalesce(excludedTags, []),\n  language,\n  "order": coalesce(order, 0),\n  status\n},\n    "productTypeScopes": productTypeScopes[]{\n      productType,\n      "ruleIds": priorityList[]._ref\n    }\n  }\n': ControlPlaneQueryResult
    '\n  *[_type == "skuEnrichment" && status == "approved" && product.productGid == $gid][0]{\n    "productGid": product.productGid,\n    headline,\n    editorialCopy,\n    "lifestyleImages": lifestyleImages[]{\n      "url": asset->url,\n      "altText": asset->altText\n    },\n    launchBadge,\n    status\n  }\n': SkuEnrichmentByGidQueryResult
    '*[_id == $id][0]{status, "reviewedAt": aiEnrichment.reviewedAt}': RULE_QUERY_RESULT
  }
}
