import {defineCliConfig} from 'sanity/cli'

// Load studio .env so CLI commands (schema extract, typegen, etc.) have access
// to SANITY_STUDIO_* variables. Vite handles this automatically during `sanity dev`.
try {
  process.loadEnvFile(`${import.meta.dirname}/.env`)
} catch {}

export default defineCliConfig({
  api: {
    projectId: process.env.SANITY_STUDIO_PROJECT_ID,
    dataset: process.env.SANITY_STUDIO_DATASET || 'production',
  },
  /**
   * TypeGen scans the shared package for defineQuery calls and writes
   * result types next to them. overloadClientMethods types client.fetch
   * in both apps without manual generics. Run `pnpm typegen` after
   * schema or query changes; the generated file is gitignored and
   * regenerated by `pretypecheck` in CI and fresh clones.
   */
  typegen: {
    enabled: true,
    path: '../packages/agent-markdown/src/**/*.ts',
    schema: 'schema.json',
    generates: '../packages/agent-markdown/src/sanity.types.ts',
    overloadClientMethods: true,
  },
})
