import {getPublishedId} from 'sanity'

/**
 * Create a translation.metadata reference entry.
 * v6 shape: explicit `language` field, `_key` auto-generated by the backend.
 */
export function createReference(languageId: string, ref: string, _type: string) {
  return {
    _type: 'internationalizedArrayReferenceValue' as const,
    language: languageId,
    value: {
      _ref: getPublishedId(ref),
      _type: 'reference' as const,
      _weak: true,
    },
  }
}
